FROM badlandsmodel/badlands-base:python3
MAINTAINER Tristan Salles

# install extras in a new layer
RUN pip3 install --no-cache-dir plotly \
  cmocean \
  pyevtk \
  colorlover

# install badlands
WORKDIR /workspace/lib
RUN git clone https://github.com/badlands-model/badlands.git && \
    cd badlands/badlands && \
    python3 setup.py install

#
#RUN git clone https://github.com/badlands-model/badlands-companion.git && \
#    pip install --no-cache-dir -e /build/pyBadlands-Companion && \
#    mkdir /workspace/companion && \
#    mv /build/pyBadlands-Companion/notebooks/* /workspace/companion/

# setup space for working in
VOLUME /live/share
WORKDIR /live

# install badlands workshop and examples
RUN git clone https://github.com/badlands-model/badlands-workshop.git && \
  mv badlands-workshop/workshop . && \
  mv badlands-workshop/examples .


ENV LD_LIBRARY_PATH=/live/lib/:/live/share

EXPOSE 8888
ENV TINI_VERSION v0.18.0
ENTRYPOINT ["/usr/local/bin/tini", "--"]

EXPOSE 9999

# note we use xvfb which to mimic the X display for lavavu
ENTRYPOINT ["/usr/local/bin/xvfbrun.sh"]

# launch notebook
CMD /usr/local/bin/run-jupyter.sh
