FROM badlandsmodel/badlands-base:python3
MAINTAINER Tristan Salles

# install extras in a new layer
RUN pip3 install --no-cache-dir plotly \
  cmocean \
  pyevtk \
  colorlover

# install badlands
RUN pip3 install --no-cache-dir badlands badlands-companion

# setup space for working in
VOLUME /live/share
WORKDIR /live

# install badlands workshop, companion and examples
RUN git clone https://github.com/badlands-model/badlands-workshop.git && \
  mv badlands-workshop/workshop . && \
  mv badlands-workshop/examples . && \
  mv badlands-workshop/companion .

ENV LD_LIBRARY_PATH=/live/lib/:/live/share

EXPOSE 8888
ENV TINI_VERSION v0.18.0
ENTRYPOINT ["/usr/local/bin/tini", "--"]

EXPOSE 9999

# note we use xvfb which to mimic the X display for lavavu
ENTRYPOINT ["/usr/local/bin/xvfbrun.sh"]

# launch notebook
CMD /usr/local/bin/run-jupyter.sh
